In [1]:
import pandas as pd

In [17]:
data = pd.read_csv("new.csv")

In [45]:
newData = pd.DataFrame(columns=data.columns)
for c in data.country.unique():
    country = data[data["country"] == c]
    
    urbans = country.urban
    urbans = (urbans-min(urbans)) / (max(urbans) - min(urbans))
    country['urban'] = urbans
    
    temps = country.temp
    temps = (temps-min(temps))/(max(temps)-min(temps))
    country['temp'] = temps
    newData = newData.append(country)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [47]:
newData.sort_values(by=['year','country'], inplace=True)
newData

     Unnamed: 0  year                   country     forest     urban      temp
0             0  1990               Afghanistan   2.067825  0.000000  0.378298
1             1  1990                   Albania  28.788321  0.000000  0.425543
2             2  1990                   Algeria   0.699908  0.000000  0.509427
3             3  1990                    Angola  48.909922  0.000000  0.442708
4             4  1990                 Argentina  12.713534  0.000000  0.566582
5             5  1990                   Armenia  11.766772  1.000000  0.421948
6             6  1990                 Australia  16.732098  0.950786  0.544223
7             7  1990                   Austria  45.725357  1.000000  0.643338
8             8  1990                Azerbaijan  10.238293  0.866216  0.401864
9             9  1990                Bangladesh  11.477299  0.000000  0.381232
10           10  1990                   Belarus  38.355354  0.000000  0.804943
11           11  1990                    Belize  70.847435  1.000000  0.281322
12           12  1990                     Benin  51.090812  0.000000  0.514384
13           13  1990                    Bhutan  53.650451  0.000000  0.357623
14           14  1990                   Bolivia  57.966399  0.000000  0.509875
15           15  1990                  Botswana  24.205530  0.000000  0.716979
16           16  1990                    Brazil  65.409888  0.000000  0.102875
17           17  1990                  Bulgaria  30.073217  0.000000  0.438536
18           18  1990              Burkina Faso  25.025585  0.000000  0.569766
19           19  1990                   Burundi  11.253894  0.000000  0.142046
20           20  1990                  Cambodia  73.328801  0.000000  0.297979
21           21  1990                  Cameroon  51.439572  0.000000  0.507388
22           22  1990                    Canada  38.299073  0.000000  0.000000
23           23  1990  Central African Republic  36.213041  0.000000  0.439680
24           24  1990                      Chad   5.324809  0.000000  0.393725
25           25  1990                     Chile  20.527698  0.000000  0.402951
26           26  1990                     China  16.738008  0.000000  0.319129
27           27  1990                  Colombia  58.059486  0.000000  0.345563
28           28  1990                Costa Rica  50.215433  0.000000  0.383749
29           29  1990                   Croatia  33.088893  0.000000  0.531276
...         ...   ...                       ...        ...       ...       ...
3522       3571  2013              Sierra Leone  40.410086  1.000000  0.720159
3523       3572  2013                  Slovakia  40.334387  0.000000  1.000000
3524       3573  2013                  Slovenia  61.946375  1.000000  1.000000
3525       3574  2013           Solomon Islands  78.463737  1.000000  0.533064
3526       3575  2013                   Somalia  10.387669  1.000000  1.000000
3527       3576  2013              South Africa   7.617737  1.000000  0.051839
3528       3577  2013               South Korea  63.603718  0.980598  1.000000
3529       3578  2013                     Spain  36.683793  1.000000  0.746098
3530       3579  2013                 Sri Lanka  33.219582  0.005895  1.000000
3531       3580  2013                     Sudan   8.231806  1.000000  0.957202
3532       3581  2013                  Suriname  98.330769  0.420885  0.426185
3533       3582  2013                 Swaziland  33.534884  0.971516  0.000000
3534       3583  2013                    Sweden  68.917857  1.000000  0.888471
3535       3584  2013               Switzerland  31.541654  0.542653  0.642326
3536       3585  2013                Tajikistan   2.937982  0.017067  1.000000
3537       3586  2013                  Thailand  31.981444  1.000000  1.000000
3538       3587  2013                      Togo   4.184593  1.000000  0.685016
3539       3588  2013                   Tunisia   6.569258  1.000000  1.000000
3540       3589  2013                    Turkey  14.955498  1.000000  0.932260
3541       3590  2013              Turkmenistan   8.782159  1.000000  1.000000
3542       3591  2013                    Uganda  11.706563  1.000000  0.974125
3543       3592  2013                   Ukraine  16.594283  1.000000  1.000000
3544       3593  2013      United Arab Emirates   3.833493  1.000000  0.874036
3545       3594  2013                   Uruguay  10.281796  1.000000  0.000000
3546       3595  2013                Uzbekistan   7.621392  0.979560  1.000000
3547       3596  2013                 Venezuela  53.298339  1.000000  0.697697
3548       3597  2013                   Vietnam  46.812010  1.000000  1.000000
3549       3598  2013                     Yemen   1.039832  1.000000  1.000000
3550       3599  2013                    Zambia  65.871481  1.000000  0.000000
3551       3600  2013                  Zimbabwe  37.965103  0.654993  0.000000

[3552 rows x 6 columns]

In [48]:
newData.to_csv("newData.csv")

In [52]:
normData = pd.DataFrame(columns=data.columns)
for c in data.country.unique():
    country = data[data["country"] == c]

    urbans = country.urban
    urbans = urbans / max(urbans)
    country['urban'] = urbans
    
    temps = country.temp
    temps = temps /max(temps)
    country['temp'] = temps
    normData = newData.append(country)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [58]:
normData = normData[:3552]
normData.to_csv("normData.csv")